in .venv\Lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py

line 470


self.trainer._logger_connector._callback_metrics.update({
        'train_size': 1835.0,
        'batch_size': 8.0,
        'val_size': 403.0,
        'train_loss': 0.6215146780014038,
        'train_accuracy': 0.75,
        'lr': 9.999999747378752e-05,
        'val_loss': 0.4828428030014038,
        'val_accuracy': 0.6666666865348816,
        'metric_to_track': 0.4828428030014038,
        'epoch': 51,
        'step': 11873
    })